name: Run PostgreSQL manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PostgreSQL manually
        run: |
          $pgsql = "C:\Program Files\PostgreSQL\14\bin"
          $data = "$env:RUNNER_TEMP\pgdata"

          # Initialize database cluster
          & "$pgsql\initdb.exe" -D "$data" -U postgres --no-locale --encoding=UTF8 --pwfile=<(echo P@ssw0rd!)

          # Start PostgreSQL in background
          Start-Process -FilePath "$pgsql\pg_ctl.exe" -ArgumentList "start -D `"$data`" -l logfile" -NoNewWindow -PassThru

          # Wait for server to be ready
          Start-Sleep -Seconds 5
        shell: powershell

      - name: Test connection
        run: |
          "SELECT version();" | "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -h localhost
        env:
          PGPASSWORD: P@ssw0rd!
        shell: powershell
