name: Run MongoDB manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable and start MongoDB service
        shell: powershell
        run: |
          Set-Service -Name MongoDB -StartupType Manual
          Start-Service -Name MongoDB
          Start-Sleep -Seconds 10
          Get-Service -Name MongoDB

      - name: Verificar porta 27017 aberta
        shell: powershell
        run: |
          netstat -ano | Select-String "27017"

      - name: Testar conexão com MongoDB usando pymongo (Python)
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Instalar pymongo
        run: pip install pymongo

      - name: Testar ping no MongoDB
        run: |
          python -c "
          from pymongo import MongoClient
          client = MongoClient('mongodb://localhost:27017/')
          print(client.admin.command('ping'))
          "
