name: Run MongoDB manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable and start MongoDB service
        shell: powershell
        run: |
          Set-Service -Name MongoDB -StartupType Manual
          Start-Service -Name MongoDB
          Start-Sleep -Seconds 10
          Get-Service -Name MongoDB

      - name: Verificar caminho do mongosh.exe
        shell: pwsh
        run: |
          $mongoshPath = (Get-Command mongosh.exe -ErrorAction SilentlyContinue).Source
          if (-not $mongoshPath) {
            # Tente caminho fixo conhecido para mongosh do runner:
            $possiblePath = "C:\Program Files\MongoDB\mongosh\2.5.6\bin\mongosh.exe"
            if (Test-Path $possiblePath) {
              $mongoshPath = $possiblePath
            } else {
              Write-Error "mongosh.exe não encontrado."
              exit 1
            }
          }
          Write-Host "mongosh encontrado em: $mongoshPath"
      
          # Testa conexão ping
          & $mongoshPath --eval "db.runCommand({ ping: 1 })"
