name: Run PostgreSQL manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up and start PostgreSQL manually
        run: |
          $pgsql = "C:\Program Files\PostgreSQL\14\bin"
          $data = "$env:RUNNER_TEMP\pgdata"
          $pwFile = "$env:RUNNER_TEMP\pgpass.txt"
          $logFile = "$env:RUNNER_TEMP\pg_logfile.txt"
          
          # Escreve a senha do usuário postgres
          "P@ssw0rd!" | Out-File -FilePath $pwFile -Encoding ascii
          
          # Inicializa o banco de dados
          & "$pgsql\initdb.exe" -D "$data" -U postgres --no-locale --encoding=UTF8 --pwfile="$pwFile"
          
          # Inicia o PostgreSQL na porta 5433
          & "$pgsql\pg_ctl.exe" start -D "$data" -l "$logFile" -o "--port=5433"
          
          # Aguarda inicialização
          Start-Sleep -Seconds 5
          
          # Cria usuário 'test' com senha 'test'
          & "$pgsql\psql.exe" -U postgres -p 5433 -d postgres -c "CREATE USER test WITH PASSWORD 'test';"
          
          # Cria banco de dados 'my_db'
          & "$pgsql\psql.exe" -U postgres -p 5433 -d postgres -c "CREATE DATABASE my_db OWNER test;"
          
          # Concede permissões
          & "$pgsql\psql.exe" -U postgres -p 5433 -d my_db -c "GRANT ALL PRIVILEGES ON DATABASE my_db TO test;"
        shell: powershell


      - name: Test PostgreSQL connection
        run: |
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -h localhost -p 5433 -c "SELECT version();"
        env:
          PGPASSWORD: P@ssw0rd!
        shell: powershell

