name: Run MongoDB manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable and start MongoDB service
        shell: powershell
        run: |
          Set-Service -Name MongoDB -StartupType Manual
          Start-Service -Name MongoDB
          Start-Sleep -Seconds 10
          Get-Service -Name MongoDB

      - name: List MongoDB bin folder
        run: Get-ChildItem "C:\Program Files\MongoDB\Server\7.0\bin" | Select-Object Name
        shell: powershell