name: Run MongoDB manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable and start MongoDB service
        shell: powershell
        run: |
          Set-Service -Name MongoDB -StartupType Manual
          Start-Service -Name MongoDB
          Start-Sleep -Seconds 10
          Get-Service -Name MongoDB

      - name: Testar o MongoDB (rápido)
        shell: pwsh
        run: |
          $basePath = "C:\Program Files\MongoDB"
          $mongoshPath = Get-ChildItem -Path $basePath -Recurse -Filter "mongosh.exe" -ErrorAction SilentlyContinue -File |
            Select-Object -ExpandProperty FullName -First 1
      
          if (-not $mongoshPath) {
            Write-Error "mongosh.exe não encontrado em $basePath."
            exit 1
          }
      
          Write-Host "Executando mongosh em: $mongoshPath"
          & $mongoshPath --eval "db.runCommand({ ping: 1 })"

