name: Run PostgreSQL manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up and start PostgreSQL manually
        run: |
          $pgsql = "C:\Program Files\PostgreSQL\14\bin"
          $data = "$env:RUNNER_TEMP\pgdata"
          $pwFile = "$env:RUNNER_TEMP\pgpass.txt"
      
          # Write password to file
          "P@ssw0rd!" | Out-File -FilePath $pwFile -Encoding ascii
      
          # Initialize database
          & "$pgsql\initdb.exe" -D "$data" -U postgres --no-locale --encoding=UTF8 --pwfile="$pwFile"
      
          # Start PostgreSQL in background
          & "$pgsql\pg_ctl.exe" start -D "$data" -l "$env:RUNNER_TEMP\pg_logfile.txt"
      
          # Wait for startup
          Start-Sleep -Seconds 5
        shell: powershell


      - name: Test PostgreSQL connection
        run: |
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -h localhost -c "SELECT version();"
        env:
          PGPASSWORD: P@ssw0rd!
        shell: powershell

