name: Test PostgreSQL on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start PostgreSQL service dynamically
        run: |
          $pgService = Get-Service | Where-Object { $_.Name -like "postgresql-x64-*" -and $_.Status -eq "Stopped" } | Select-Object -First 1
          if ($pgService) {
            Start-Service -Name $pgService.Name
            Write-Output "Started PostgreSQL service: $($pgService.Name)"
          } else {
            Write-Error "No stopped PostgreSQL service found."
            exit 1
          }
        shell: powershell

      - name: Wait for PostgreSQL
        run: Start-Sleep -Seconds 5
        shell: powershell

      - name: Test connection to PostgreSQL
        run: psql -U postgres -c "SELECT version();"
        env:
          PGPASSWORD: 'P@ssw0rd!'
        shell: bash
