name: Run MongoDB manually on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable and start MongoDB service
        shell: powershell
        run: |
          Set-Service -Name MongoDB -StartupType Manual
          Start-Service -Name MongoDB
          Start-Sleep -Seconds 10
          Get-Service -Name MongoDB

      - name: Encontrar mongosh.exe em Program Files
        shell: pwsh
        run: |
          $pathsToCheck = @(
            "C:\Program Files\MongoDB",
            "C:\Program Files (x86)\MongoDB"
          )
      
          $mongoshPath = $null
          foreach ($path in $pathsToCheck) {
            if (Test-Path $path) {
              $mongoshPath = Get-ChildItem -Path $path -Recurse -Filter "mongosh.exe" -ErrorAction SilentlyContinue -File | Select-Object -First 1 -ExpandProperty FullName
              if ($mongoshPath) { break }
            }
          }
      
          if (-not $mongoshPath) {
            Write-Error "mongosh.exe não encontrado em nenhum Program Files."
            exit 1
          }
      
          Write-Host "mongosh.exe encontrado em: $mongoshPath"
          & $mongoshPath --eval "db.runCommand({ ping: 1 })"
